

# This compose file is useful for testing https.
# The .env file sets ENVVARS for the Docker CLI used by this compose file.
---
version: "3"
services:
  datastore_api_simple:
    build: . #/datastore_client_new
    # dockerfile: Dockerfile
    ports:
      - 8890:8050
    dns:
      - 8.8.8.8
      - 8.8.4.4
    stdin_open: true
    tty: true
    command: ["gunicorn", "--reload", "-b :8050",  "-t 90", "app:server"]
    container_name: datastore_api_simple
    # hostname: datastore_client_new
    volumes:
      - ./src:/app
    env_file:
      - ./.env

networks:
  default:
    name: a2cps_datastore_net
    external: true
